### ISSUE TITLE
您好~不能显示

### ISSUE THREAD

**Issue by 110117ab** [niorgai/Android-Resource-Usage-Count#14]
您好~我这边完全没有显示~但是我在colors.xml中又看到左边的颜色图标有轻微的移动，证明正在计算~但是显示不出来~请问这是怎么回事，我的版本是3.0 Canary8~

**Comment by niorgai** [comment]
#12 3.0 的问题还是出了 stable 版本我再跟进吧, 尝鲜要付出代价的~ =.=

**Comment by niorgai** [comment]
Can you try beta 6? It seems like have been fixed.

Version Info:

Android Studio 3.0 Beta 6
Build #AI-171.4333198, built on September 14, 2017
JRE: 1.8.0_152-release-915-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
