### ISSUE TITLE
Colors Readability

### ISSUE THREAD

**Issue by Sottti** [niorgai/Android-Resource-Usage-Count#15]
Hi, thanks for the plugin is great!

I'm looking for zeros (0) all the time because those are the ones that might be the useless resources and more important to identify to be removed. Unfortunately, the colour that is more noticeable is read that and the grey is very difficult to see quickly.

Would be great to have the possibility of customizing the colours or at least, having the red colour for the zeros (0) so they are easy and quick to see.

Thanks!

**Comment by niorgai** [comment]
Well, i develop this plugin to look for the resource which has been used for more than one times. If i want to modify these resource, i must create a new resource and use the new one. 
For these reason, i set them to red color and set zeros to grey.

However, I will try to add the feature to custom color.

**Comment by Sottti** [comment]
Oh, now it makes sense. I never thought about that use case. To me the most problematic resources are the ones that I'm not using anymore (0 usages) so I'm always looking for those. Thanks!

**Comment by niorgai** [comment]
Now you can update this plugin to 2.0 in Android Studio official repo.
You can custom color in `Preferences`-`Other Settings`-`Android Resource Usage Count`.

Thank you for your advice.

**Comment by Sottti** [comment]
Thanks, this is great now!
