### ISSUE TITLE
Add option to display recource count only for not used resources

### ISSUE THREAD

**Issue by igorwojda** [niorgai/Android-Resource-Usage-Count#19]
For me personally, this plugin makes sense only to easily track not used resources.

We could even show some icon with warning (or error) instead of 0 number

**Comment by niorgai** [comment]
Well, i develop this plugin to look for the resource which has been used for more than one times. If i want to modify these resource, i must create a new resource and use the new one.

Maybe i will add this feature, it's a little busy now.

**Comment by niorgai** [comment]
Version 2.1 have add this feature.
