### ISSUE TITLE
AS plugins 里搜不到...

### ISSUE THREAD

**Issue by jp1017** [niorgai/Android-Resource-Usage-Count#2]
Untill now. ...

**Comment by niorgai** [comment]
... 第一次开发不懂规矩..发布的时候有个坑没注意..1.1已经提交审核了..如果审核通过能搜到我会添加到博客说明里去..

**Comment by androidzhang** [comment]
请问作者是提交到jcenter仓库了？

**Comment by niorgai** [comment]
没有   只是发布的时候没有添加 AS 的支持. IntelliJ IDEA 的仓库是可以搜索到的

**Comment by LouisMari1991** [comment]
我也搜不到哇，请问你们是怎么找到的哇？

**Comment by niorgai** [comment]
@MariShunxiang 目前还搜不到, 直接到 JetBrains 的仓库下载 1.0 就好... [地址](https://plugins.jetbrains.com/plugin/9885-android-resource-usage-count?). 

不过可以在 IntelliJ IDEA 的仓库找到...

**Comment by jp1017** [comment]
@MariShunxiang 手动下载jar, as本地导入...

**Comment by llew2011** [comment]
手动下载，本地导入

**Comment by niorgai** [comment]
已经可以搜索到了

**Comment by jp1017** [comment]
@niorgai Perfect, Good job, keep moving, boy...  :smile: :smile:

**Comment by LouisMari1991** [comment]
哦，明白了

**Comment by edu-lance** [comment]
请问是什么坑,我准备试试？

**Comment by niorgai** [comment]
@liuxang 发布时, 在提交页面提交 jar 包后会进去编辑页面, 在 `Supported products` 模块去掉勾选 `Determine supported products by dependencies in plugin.xml`, 改为自定义支持所需平台就好. 不算坑..我自己没注意. 或者你也可以试试在 plugin.xml 中的 dependencies 添加自己想支持的平台试试
