### ISSUE TITLE
NullPointException

### ISSUE THREAD

**Issue by RWebRTC** [niorgai/Android-Resource-Usage-Count#24]
<img width="357" alt="2017-09-19 14 16 32" src="https://user-images.githubusercontent.com/21374839/30578233-6181036c-9d45-11e7-9603-cd17d9d3d410.png">

Just when use, it appear this error, not once. Thank you! :)

**Comment by niorgai** [comment]
#17 Are u using Android Studio 3.0?

**Comment by RWebRTC** [comment]
@niorgai Yes

**Comment by niorgai** [comment]
So I will fix it after stable version release.

**Comment by RWebRTC** [comment]
Got it, Thank you.

**Comment by niorgai** [comment]
Can you try beta 6? It seems like have been fixed.

Version Info:

Android Studio 3.0 Beta 6
Build #AI-171.4333198, built on September 14, 2017
JRE: 1.8.0_152-release-915-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by RWebRTC** [comment]
@niorgai Ok, I will try. Thank you.

**Comment by renyuzhuo** [comment]
@niorgai I am sorry to say that it still has the same bug. How to see this error message to get more info ?

```
Plugin Error: Android Resource Usage Count threw an uncaught NullPointerException. Disable Plugin
```

Android Studio 3.0.1
Build #AI-171.4443003, built on November 10, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

Thank you.
