### ISSUE TITLE
没有统计数量

### ISSUE THREAD

**Issue by xiangyao0906** [niorgai/Android-Resource-Usage-Count#25]
as 3.0 beta 5 安装之后没有统计数量的显示啊

**Comment by xiangyao0906** [comment]
![image](https://user-images.githubusercontent.com/16839786/30625782-ea28f8fc-9df7-11e7-9c74-77e0cec682b8.png)

**Comment by niorgai** [comment]
#12  一样的, 我刚刚用 beta 6测试可以正常显示

**Comment by xiangyao0906** [comment]
![image](https://user-images.githubusercontent.com/16839786/30780741-de110f32-a144-11e7-8477-b32541540609.png)
win 有问题么
