### ISSUE TITLE
数量统计不准

### ISSUE THREAD

**Issue by ghost** [niorgai/Android-Resource-Usage-Count#3]
新建了一个项目，但是颜色和字符串的引用数量都显示为0。同时，如果 xml 文件超过一屏幕，没有在屏幕中显示的资源文件没有此数量标记。
<img width="434" alt="2017-08-02 21 25 22" src="https://user-images.githubusercontent.com/30451487/28875718-1ecf7608-77c9-11e7-8074-cbabecd1cc52.png">

**Comment by niorgai** [comment]
我也新建了一个项目, 都是1啊.
你手动 Find Usage 有显示引用?

另外超过一屏的我这边也有显示, 只是会"稍微"慢一点, 没有慢太多.

**Comment by ghost** [comment]
不确定什么原因，在新建立项目或者一些老项目会出现引用数都为 0 的情况，此时 Find Usage 显示的数量也为 0，但是在 Find Usage 显示正确的情况下这里也显示正确。
