### ISSUE TITLE
当项目实现国际化时，统计插件没有完全生效。

### ISSUE THREAD

**Issue by shangxiazuoyou** [niorgai/Android-Resource-Usage-Count#4]
具体场景，当我的项目使用了英文、中文简体和中文繁体（台湾）三种文字时，英文和中文简体部分string生效，绝大部分未生效，而中文繁体所有string生效。

**Comment by niorgai** [comment]
有没有尝试过重新打开项目呢? 或者重新打开资源文件. 理论上我用系统提供的 FindUsageAction 实现的功能都是一样的, 只是有时候打开会慢一点

**Comment by huangssh** [comment]
遇到同样的情况了，例如总共300个String，只有前30个显示了统计，重启和重新打开文件都无效

**Comment by shangxiazuoyou** [comment]
重启Android Studio或者重新打开strings.xml都无效。

**Comment by softrice** [comment]
同遇到 只显示前面的资源 后面都无法显示

**Comment by leo-andr** [comment]
同上 colors加上空格显示前30行  strings展示中间部分的30行 其他资源文件或多或少都有此问题

**Comment by tempersitu** [comment]
我重新打开了也无效,我的情况是简体中文完全不显示,英文和繁体中文就少部分显示.很期待能修复这个问题,因为我最逼切的就是想把没用的strings去掉.

**Comment by niorgai** [comment]
我也挺郁闷..想找一个能重现的项目试试..这边一直没法复现

**Comment by NingSo** [comment]
string 条数太多几百条就Count显示不全。。

**Comment by niorgai** [comment]
一直没法复现啊...这貌似不是必现的..你们升级下 AS 版本试试?

**Comment by yuliuyu000** [comment]
多敲几个回车然后在删除反复几遍就会发现数字就显示了。string特别多行的时候就从上面一点一点的反复操作就都有了，最好是一开始吧光标放到<resources>前面然后缩进这样就显示的快些

**Comment by niorgai** [comment]
我用 [iosched](https://github.com/google/iosched) 这个项目做了一下测试, 打开的时候确实有显示几行然后卡住的情况, 但是打 Log 发现仍然在运行, 一小会后就正常显示了. 目前来说没发现那里有问题. 希望大家多试试..

**Comment by liangju126** [comment]
string.xml只显示了前30个。。。

**Comment by niorgai** [comment]
@talentju 等一下/编辑一下/重新打开 ..编辑一下比较有效..

**Comment by hjq** [comment]
Android studio 3.0 beta6上没有生效，一条都没有统计

**Comment by niorgai** [comment]
@hjq 我刚下的这个版本可以啊..你也是这个版本吗?

Android Studio 3.0 Beta 6
Build #AI-171.4333198, built on September 14, 2017
JRE: 1.8.0_152-release-915-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
