### ISSUE TITLE
是否支持查看资源具体引用位置？有在考虑扩展吗

### ISSUE THREAD

**Issue by feelschaotic** [niorgai/Android-Resource-Usage-Count#5]

**Comment by niorgai** [comment]
其实代码中似乎已经有引用位置了..但是我没有放出来的想法, 有一个原因就是没想到好的表现形式.
另外我觉得更精简的形式是区分引用次数 0, 1, 其他用不同颜色即可, 数字都不用.

其实每个人具体需求不同, 欢迎 fork 代码实现自己需求
