### ISSUE TITLE
Count显示不全

### ISSUE THREAD

**Issue by leo-andr** [niorgai/Android-Resource-Usage-Count#6]
大概知道了  你第一次打开的资源文件在哪个位置   这个插件显示只显示了这个文件这一页的数据显示   再翻页好像没有效果  显示不全

**Comment by niorgai** [comment]
#4

**Comment by niorgai** [comment]
我用 [iosched](https://github.com/google/iosched) 这个项目做了一下测试, 打开的时候确实有显示几行然后卡住的情况, 但是打 Log 发现仍然在运行, 一小会后就正常显示了. 目前来说没发现那里有问题, 以后集中反馈到 #4  吧
