### ISSUE TITLE
请问作者我添加Jar包依赖后打开string不显示使用次数呀

### ISSUE THREAD

**Issue by LeiHolmes** [niorgai/Android-Resource-Usage-Count#7]
AndroidStudio仓库搜不到所以我下载了Jar包放入libs建立了依赖，但是没有效果。我的studio版本是2.3.2，会有影响吗？打扰啦！

**Comment by niorgai** [comment]
试试重新打开文件, 目前收到一些反馈说不稳定..但是我重现不了.

至于版本号, 主要看下面的 162, 大于145都是支持的

Android Studio 2.3.3
Build #AI-162.4069837, built on June 6, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by niorgai** [comment]
#4

**Comment by LeiHolmes** [comment]
好的，我再试试，谢谢作者。
