### ISSUE TITLE
类似 arrays/attrs/styles 等这种由多个 item 组成的 resources 的显示问题

### ISSUE THREAD

**Issue by DysaniazzZ** [niorgai/Android-Resource-Usage-Count#8]
RT，这些种类型的引用次数只标在主类型上就行了吧。

![screen shot 2017-08-04 at 9 25 13 am](https://user-images.githubusercontent.com/19492924/28950528-2ebda6be-78f7-11e7-86fd-4f6eb4b77131.png)

![screen shot 2017-08-04 at 9 21 03 am](https://user-images.githubusercontent.com/19492924/28950419-4b5a99f4-78f6-11e7-88ab-dc1228e0ae89.png)

**Comment by niorgai** [comment]
有道理.
不过实现的时候我也只能把 `item` 标签的统计去掉, 不知道有没有单独的 `item` 标签.

**Comment by shaonialife** [comment]
![image](https://user-images.githubusercontent.com/16135960/28956801-6be8a050-7921-11e7-8858-afc79007471f.png)
有单独的 item 标签的，像图片上那个 tag，使用时用 R.id.tag 方式引用 , 我通常是来给View设置tag时使用的，比如 
view.setTag(R.id.tag, someObject);
someObj = view.getTag(R.id.tag);

**Comment by niorgai** [comment]
@shaonialife 有道理..所以目前我也没想到什么好方法去区分这两种类型. @DysaniazzZ
